### ISSUE TITLE
[비정상적인 웹사이트] 브랜치 설정 필요

### ISSUE THREAD

**Issue by MadeGOD** [team-int/Web#2]
설정에서 Pages 항목에 웹에 표시할 브랜치를 gh-pages로 변경해주세요

### 비정상적인 화면
![ㅁㄴㅇㄹ](https://cdn.discordapp.com/attachments/750706097601511556/831504585095905381/Screenshot_20210413-202144_Whale.jpg)

**Comment by chul0721** [comment]
처리하였습니다.
