### ISSUE TITLE
[도매인 연동 필요] 404 css, js, html, 이미지

### ISSUE THREAD

**Issue by MadeGOD** [team-int/Web#3]
# 소개
https://team-int.github.io/Web/는 https://hello.world 와  같은 sub domain 이 아니며 pages 형식임으로 도매인 연동을 추천드립니다.

# 스크리샷 

![image](https://user-images.githubusercontent.com/63600304/115204422-0dac6680-a12b-11eb-866f-9609fb72e36b.png)

**Comment by chul0721** [comment]
연동할 도메인을 준비중이며, 아직 개발이 완료되지 않은 페이지이므로 미완성인것은 당연합니다.
